const DATA_SOURCE = 'DATA_SOURCE';
const USER_REPOSITORY = 'USER_REPOSITORY';
const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';

export {
    DATA_SOURCE,
    USER_REPOSITORY,
    PRODUCT_REPOSITORY
}
